name: Update ROA
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
  - cron: "48 * * * *"
  workflow_dispatch:

jobs:
  update:
    name: Update ROA files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      id: checkout

    - name: Run
      run: |-
        sudo apt-get install -y whois
        curl -LO https://github.com/BurntSushi/ripgrep/releases/download/14.1.0/ripgrep_14.1.0-1_amd64.deb
        sudo dpkg -i ripgrep_14.1.0-1_amd64.deb
        rm -rf ripgrep_14.1.0-1_amd64.deb
        bash script.sh AS213891:AS-WYFIX-MEMBER-DN42
        bash script.sh AS210440:AS-AKIX-MEMBER-DN42
        mv *.conf conf/
    - name: Commit files
      run: |
        git config --local user.email "bot@932.moe"
        git config --local user.name "HelloTools-bot"
        git add .
        git commit --allow-empty -m "chore: Update ROA files `date '+%Y-%m-%d %H:%M:%S'` :star: [skip ci]"
        git push
